Lots3
AlexRedisson18/Exchange pull request #11
Opened 2020-07-03 08:31 UTC by AlexRedisson18

## What was done?
- add S3

2020-07-03 13:02 UTC, akurashev requested changes

2020-07-03 13:02 UTC, akurashev commented on Gemfile
> +gem "fog-aws"
```suggestion
gem 'fog-aws'
```

2020-07-03 13:02 UTC, akurashev commented on app/controllers/lots_controller.rb
> -  respond_to :json, only: %i[create]
Hmm... Why is that removed?

2020-07-03 13:02 UTC, akurashev commented on app/controllers/lots_controller.rb
> +      :image_cache
Keep hash params at the end

```suggestion
      :image,
      :image_cache,
      interesting_category_ids: [],
      images: []
```

2020-07-03 13:02 UTC, akurashev commented on app/models/lot.rb
> +  mount_uploaders :images, ImageUploader
Move this up. Place it somewhere around relations/validations/scopes

2020-07-06 06:31 UTC, AlexRedisson18 commented on app/controllers/lots_controller.rb
> -  respond_to :json, only: %i[create]
i tried to remove it - and nothing changed
i think it doesnt work

2020-07-06 06:47 UTC, akurashev requested changes
One comment left. And fix conflicts

2020-07-06 07:00 UTC, akurashev approved these changes

2020-07-06 07:01 UTC, merged