add offers
AlexRedisson18/Exchange pull request #18
Opened 2020-08-20 07:20 UTC by AlexRedisson18

# WHAT WAS DONE
- add offers
you can just create offer

2020-08-23 14:08 UTC, akurashev requested changes
Why do you have both `yarn.lock` and `package-lock.json`? Do you use yarn or npm for JS package management?

2020-08-23 14:08 UTC, akurashev commented on app/javascript/styles/lots_show.sass
> +.lot-description
No styles

2020-08-23 14:08 UTC, akurashev commented on app/javascript/custom/offer.js
> +  $(".js-suggested-lot").focus(function() {
Why `focus` and not `click`?

2020-08-23 14:08 UTC, akurashev commented on app/models/offer.rb
> +  enum status: %i[pendind rejected confirmed]
Add shoulda-matcher in test for this

2020-08-23 14:08 UTC, akurashev commented on app/models/offer.rb
> +  validates :suggested_lot, uniqueness: { scope: :requested_lot }
And for these

2020-08-23 14:08 UTC, akurashev commented on app/controllers/offers_controller.rb
> +  def create
Test?

2020-08-24 06:42 UTC, AlexRedisson18 commented on app/javascript/custom/offer.js
> +  $(".js-suggested-lot").focus(function() {
because focus works during and after click
click works just during click

2020-08-25 07:46 UTC, akurashev requested changes

2020-08-25 07:46 UTC, akurashev commented on app/controllers/offers_controller.rb
> +    if @suggested_lot.present? && @suggested_lot.user == current_user
`@suggested_lot` always presents at this line. If there is no such lot then `Lot.find()` will raise NotFound error

2020-08-25 07:46 UTC, akurashev commented
> Why do you have both `yarn.lock` and `package-lock.json`? Do you use yarn or npm for JS package management?

@AlexRedisson18 What about this?

2020-08-25 09:46 UTC, akurashev approved these changes

2020-08-25 09:56 UTC, merged