Offers messages
AlexRedisson18/Exchange pull request #19
Opened 2020-08-31 10:39 UTC by AlexRedisson18

## WHAT WAS DONE
tabs in profile
new assotiations
extended views
NO tests

2020-09-01 17:01 UTC, akurashev requested changes

2020-09-01 17:01 UTC, akurashev commented on app/javascript/styles/homepage.sass
> +  overflow-y: scroll
It'll add scrollbar even if there's nothing to scroll. Why now `overflow-y: auto`?

2020-09-01 17:01 UTC, akurashev commented on app/models/offer.rb
> +  validates :suggested_lot, presence: { message: 'choose suggested lot' }
Don't you need to validate `requested_lot` for presence as well?

2020-09-01 17:01 UTC, akurashev commented on assa.html
> +</html>
WTF?

2020-09-01 17:01 UTC, akurashev commented on app/controllers/lots_controller.rb
> +    @offers_i_made = Offer.joins(:suggested_lot).where('lots.user_id = ?', current_user)
```suggestion
    @offers_i_made = current_user.outgoing_offers
```

2020-09-01 17:01 UTC, akurashev commented on app/views/offers/_offer.html.slim
> +    = form_with model: @message, url: messages_path, method: :post, id: 'new-message', html: { class: "",:'data-type' => 'json' } do |f|
This form is for creating new messages. There's no way to edit old ones. So just use `Message.new` instead of `@message` here. And remove `@message` from controllers.

2020-09-01 17:01 UTC, akurashev commented on app/views/offers/_offer.html.slim
> +      = f.hidden_field :user_id, value: current_user.id
Never pass current_user through form. There's just no point in doing this. Just take current_user in controller and add it to message params if you need to.

2020-09-01 17:01 UTC, akurashev commented on app/views/profiles/show.html.slim
> +        | recived offers
`recived` -> `received`

2020-09-01 17:01 UTC, akurashev commented on app/views/profiles/show.html.slim
> +      = render partial: "offers/offer", collection: @outgoing_offers, locals: { lot_img: :requested_lot, lot_msg: :suggested_lot}
Would this work?

```suggestion
      = render @outgoing_offers, locals: { lot_img: :requested_lot, lot_msg: :suggested_lot}
```

2020-09-01 17:01 UTC, akurashev commented on app/views/offers/_form.html.slim
> +              = messages_form.hidden_field :user_id, value: current_user.id
The same here. Don't pass user_id like this

2020-09-02 09:21 UTC, AlexRedisson18 commented on app/javascript/styles/homepage.sass
> +  overflow-y: scroll
`overflow-y: scroll` looks more neat and does not twitch

2020-09-02 09:41 UTC, AlexRedisson18 commented on app/views/profiles/show.html.slim
> +      = render partial: "offers/offer", collection: @outgoing_offers, locals: { lot_img: :requested_lot, lot_msg: :suggested_lot}
no

2020-09-02 10:58 UTC, AlexRedisson18 commented on app/views/offers/_form.html.slim
> +              = messages_form.hidden_field :user_id, value: current_user.id
other methods didnt work
i change @message to  current_user.messages.new(params)
but i has error: messages.user - must exist

2020-09-03 07:37 UTC, akurashev commented on app/views/messages/_form.html.slim
> +/ = messages_form.hidden_field :user_id, value: current_user.id
Remove this

2020-09-03 07:40 UTC, merged