Lots
AlexRedisson18/Exchange pull request #8
Opened 2020-06-12 10:28 UTC by AlexRedisson18

add Create new lot / edit lot functionality / Title, Condition, Description, Price
add some tests

2020-06-17 08:21 UTC, akurashev requested changes

2020-06-17 08:21 UTC, akurashev commented on db/migrate/20200423070105_create_lots.rb
> +      t.string :image
Never change already commited migrations!
Create a new one which would update DB

2020-06-17 08:21 UTC, akurashev commented on spec/requests/lots_request_spec.rb
> +    end
There's no point to include `with current user` context in this case. When user is not signed in, there's no any current user.

```suggestion
    context 'when user is NOT signed in' do
      it_behaves_like 'response with code', code: 200, request_required: true
    end
```

2020-06-17 08:21 UTC, akurashev commented on spec/requests/lots_request_spec.rb
> +      include_context 'with current user', signed_in: false
Same here in all similar cases below

2020-06-18 10:03 UTC, onenaviio approved these changes

2020-06-24 05:56 UTC, closed without merging