Lots2
AlexRedisson18/Exchange pull request #9
Opened 2020-06-24 06:47 UTC by AlexRedisson18

add category and categories
add basic validations (index, new, create)
add conditional validation for interesting categories / price
change bootstrap select-tag style  to 'bootstrap-select' package style

2020-06-28 06:50 UTC, akurashev requested changes

2020-06-28 06:50 UTC, akurashev commented on db/migrate/20200423070105_create_lots.rb
> +      t.string :image
Again, changed migration

2020-06-28 06:50 UTC, akurashev commented on db/schema.rb
> +    t.bigint "lot_id"
Where is it from?

2020-06-28 06:50 UTC, akurashev commented on app/models/lot.rb
> +  belongs_to :category, optional: true
Why optional?

2020-06-28 06:50 UTC, akurashev commented on spec/support/shared_examples/requests/common.rb
> +shared_examples 'response with code' do |code:, request_required: false|
No need of `request_required` param here. It's always `true`

2020-06-28 06:50 UTC, akurashev commented on spec/requests/lots_request_spec.rb
> +  end
```suggestion
  describe 'POST #create' do
    subject(:make_request) { post :create, params: { lot: lot } }

    let(:category) { create(:category) }
    let(:lot) { attributes_for(:lot, category_id: category) }
    
    context 'when user is signed in' do
      include_context 'with current user'

      it 'creates new lot' do
        expect { make_request }.to change(Lot, :count).from(0).to(1)
      end
    end

    context 'when user is NOT signed in' do
      it_behaves_like 'response with code', code: 302, request_required: true
    end
  end
```

2020-06-29 06:32 UTC, AlexRedisson18 commented on db/migrate/20200423070105_create_lots.rb
> +      t.string :image
this is the same change

2020-06-29 06:43 UTC, AlexRedisson18 commented on db/schema.rb
> +    t.bigint "lot_id"
hm...
mb jointable did this?

2020-06-29 11:10 UTC, mkalinin approved these changes
Well done 👍

2020-06-29 11:11 UTC, akurashev commented
> Well done 👍

Medium well, please

2020-06-29 11:11 UTC, akurashev approved these changes

2020-06-29 11:12 UTC, merged

2020-06-29 11:14 UTC, mkalinin commented
> Medium well, please

lmfao